### ISSUE TITLE
1.21.1: Errors in console

### ISSUE THREAD

**Issue by Geitenijs** [kangarko/Protect#8]
After updating to Paper 1.21.1 from 1.21 I'm getting these errors in my console whenever a player joins.

`[15:15:36 WARN]: [Protect] Task #91069 for Protect v1.1.8 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.protect.lib.remain.nbt.NBTReflectionUtil
        at Protect.jar/org.mineacademy.protect.lib.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule$RuleCheck.check0(Rule.java:351) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule$RuleCheck.checkPlayerInventory(Rule.java:240) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule.filter(Rule.java:181) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule.filterPlayer(Rule.java:139) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.listener.ScanListener.scanPlayerIf(ScanListener.java:197) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.listener.ScanListener.lambda$onJoin$0(ScanListener.java:45) ~[Protect.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
        at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at Protect.jar/org.mineacademy.protect.lib.remain.nbt.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:50) ~[Protect.jar:?]
        ... 15 more`

`[15:15:25 WARN]: [Protect] Task #25151 for Protect v1.1.8 generated an exception
java.lang.ExceptionInInitializerError: null
        at Protect.jar/org.mineacademy.protect.lib.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule$RuleCheck.check0(Rule.java:351) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule$RuleCheck.checkPlayerInventory(Rule.java:240) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule.filter(Rule.java:181) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.operator.Rule.filterPlayer(Rule.java:139) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.listener.ScanListener.scanPlayerIf(ScanListener.java:197) ~[Protect.jar:?]
        at Protect.jar/org.mineacademy.protect.listener.ScanListener.lambda$onJoin$0(ScanListener.java:45) ~[Protect.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
        at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
        at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
        at Protect.jar/org.mineacademy.protect.lib.remain.nbt.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:50) ~[Protect.jar:?]
        ... 15 more`

[debug.zip](https://github.com/user-attachments/files/16573785/debug.zip)

**Comment by kangarko** [comment]
No yet ready for 1.21.1, sorry, will be updating next week.

**Comment by Geitenijs** [comment]
No worries, enjoy your holiday :)

**Comment by kangarko** [comment]
Looks like it's fixed now :)

![a](https://i.imgur.com/SHvFhGU.png)

**Comment by Geitenijs** [comment]
Great, thanks for your help! Amazing support as usual
